### ISSUE TITLE
Investigate support for PausingDispatcher

### ISSUE THREAD

**Issue by GediminasZukas** [vinted/coper#5]
Androidx Fragment has such APIs to launch coroutines:

```
viewLifecycleOwner.lifecycleScope.launchWhenResumed { }
lifecycleScope.launchWhenResumed { } 
```

Unfortunately, those coroutine builders are using `PausingDispatcher` which is currently not supported by coper. Exception is thrown here: https://github.com/vinted/coper/blob/master/library/src/main/java/com/vinted/coper/CoperImpl.kt#L35

**Comment by samuolis** [comment]
It will go to next release
